# Generated by Django 5.2.17 on 2026-09-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_alter_company_id_alter_project_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='reason',
            field=models.TextField(db_default=''),
        ),
        migrations.CreateModel(
            name='VersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('requirement', models.TextField()),
                ('type', models.CharField(choices=[('Functional', 'Functional'), ('Non-Functional', 'Non-Functional'), ('Security', 'Security'), ('Performance', 'Performance'), ('UI/UX', 'UI/UX')], max_length=20)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('clear', 'clear'), ('incomplete', 'incomplete'), ('conflict', 'conflict'), ('duplicate', 'duplicate')], max_length=20)),
                ('editedat', models.DateTimeField(auto_now_add=True)),
                ('editedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.project')),
            ],
        ),
    ]
