# Generated by Django 5.2.17 on 2026-09-27 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_requirement_reason_versionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionhistory',
            name='requirementtext',
            field=models.TextField(db_default=''),
        ),
        migrations.AlterField(
            model_name='versionhistory',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.requirement'),
        ),
    ]
