# Generated by Django 5.2.17 on 2026-09-28 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_versionhistory_requirementtext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestedrequirement', models.TextField(db_default='')),
                ('comment', models.TextField()),
                ('suggestedtype', models.CharField(choices=[('Functional', 'Functional'), ('Non-Functional', 'Non-Functional'), ('Security', 'Security'), ('Performance', 'Performance'), ('UI/UX', 'UI/UX')], max_length=20)),
                ('suggestedpriority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('suggestedat', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.project')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.requirement')),
                ('suggestedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.user')),
            ],
        ),
    ]
