# Generated by Django 5.2.17 on 2026-09-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_requirementsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementsuggestion',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
