# Generated by Django 5.2.17 on 2026-10-02 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0006_alter_requirementsuggestion_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionhistory',
            name='suggestedby',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestedby', to='appname.user'),
        ),
        migrations.AlterField(
            model_name='requirementsuggestion',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
