# Generated by Django 5.2.17 on 2026-10-03 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0007_versionhistory_suggestedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='implementation_status',
            field=models.CharField(choices=[('notstarted', 'NotStarted'), ('inprogress', 'InProgress'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='notstarted', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_end_date', models.DateTimeField()),
                ('planned_number_of_sprints', models.IntegerField()),
                ('planned_number_of_team_members', models.IntegerField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('inprogress', 'InProgress'), ('completed', 'Completed'), ('onhold', 'OnHold'), ('cancelled', 'Cancelled')], max_length=20)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appname.project')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('inprogress', 'InProgress'), ('completed', 'Completed'), ('onhold', 'OnHold'), ('cancelled', 'Cancelled')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.project')),
            ],
        ),
    ]
