# Generated by Django 5.2.17 on 2026-10-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0008_project_end_at_requirement_implementation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplanning',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('inprogress', 'InProgress'), ('completed', 'Completed'), ('onhold', 'OnHold'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
    ]
