# Generated by Django 5.2.17 on 2026-10-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0009_alter_projectplanning_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplanning',
            name='status',
            field=models.CharField(choices=[('notplanned', 'NotPlanned'), ('planned', 'Planned'), ('inprogress', 'InProgress'), ('completed', 'Completed'), ('onhold', 'OnHold'), ('cancelled', 'Cancelled')], default='notplanned', max_length=20),
        ),
    ]
