# Generated by Django 5.2.17 on 2026-10-04 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0010_alter_projectplanning_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appname.sprint'),
        ),
    ]
