# Generated by Django 5.2.17 on 2026-10-04 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0011_requirement_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplanning',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectplanning',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appname.user'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appname.user'),
        ),
    ]
